
#include <string>

using namespace std;

/** 
 * Reads a file into a string
 * @param filename The file to read from 
 * @return a string containing filename's contents
 */
std::string file_to_string(const std::string & filename);



/** 
 * Reads a string that has lines of airport information
 * @param string The string generated by file_to_string
 * @return a vector containing airports
 */

vector<string> manipulate_string(string s);

/** 
 * Reads a string that contains airport information
 * @param string s The airport string to sort the information
 * @param string token The string that we use to separate each element in the string
 * @return a string vector containing airport's information corresponding to the Airport Node
 */
vector<string> manipulate_string(string s, string token);

/**
 * Reads a string that contains airline informatio
 * @param input the airline string to sort the information
 * @param token the string that we use to seperate each element in the string
 * @return a string vector containing airline's information corresponding to the Airline node
 */
vector<string> manipulate_route(string input, string token);